const articles = [
  {
    source: {
      id: 'lenta',
      name: 'Lenta',
    },
    author: null,
    title: 'Тренер «Ливерпуля» засомневался в способности Месси принести пользу АПЛ',
    description: 'Главный тренер английского «Ливерпуля» Юрген Клопп прокомментировал возможный переход нападающего каталонской «Барселоны» Лионеля Месси в клуб Английской премьер-лиги (АПЛ). «Я не уверен, что лиге нужно такое усиление. Месси никогда не играл в другом чемпиона…',
    url: 'https://lenta.ru/news/2020/08/28/klopp/',
    urlToImage: 'https://icdn.lenta.ru/images/2020/08/28/17/20200828171452116/share_cf3f0b0c960a867aa6b8727742f91658.jpg',
    publishedAt: '2020-08-28T14:56:00Z',
    content: '«» «» « ». Liverpool Echo.\r\n - (). « , . . », . , , «» .\r\n27 «» . , . - .\r\n «» . 25 «», , .\r\n « » - «» 1/4 «» (2:8). - , . 2021 .',
  },
  {
    source: {
      id: null,
      name: 'Championat.com',
    },
    author: 'Чемпионат',
    title: 'УЕФА обязал «Слован» сыграть в Лиге чемпионов дублем из-за коронавируса у физиотерапевта - Чемпионат',
    description: '<ol><li>УЕФА обязал «Слован» сыграть в Лиге чемпионов дублем из-за коронавируса у физиотерапевта  Чемпионат\r\n</li><li>«КИ Клаксвик» — «Слован» Братислава. Прогноз (к. 1.67) и ставки на матч Лиги чемпионов 19 августа 2020 года  LiveSport.Ru\r\n</li><li>Матч Лиги…',
    url: 'https://www.championat.com/football/news-4111407-uefa-objazal-slovan-sygrat-v-lige-chempionov-dublem-iz-za-koronavirusa-u-fizioterapevta.html',
    urlToImage: 'https://img.championat.com/news2/social/2/e6/4111407.jpg',
    publishedAt: '2020-08-19T20:06:01Z',
    content: '«» 1- «» - . , , Sport Aktuality.\r\n -, . «» . . , 14- .\r\n, , «» . 21 . .\r\n «» . , 15- , 1:7.',
  },
  {
    source: {
      id: null,
      name: 'Championat.com',
    },
    author: 'Чемпионат',
    title: 'Камано — в стартовом составе «Локомотива» на матч с «Ахматом» - Чемпионат',
    description: '<ol><li>Камано — в стартовом составе «Локомотива» на матч с «Ахматом»  Чемпионат\r\n</li><li>«Локомотив» — «Ахмат»: прогноз и ставка Александра Неценко  Рейтинг Букмекеров\r\n</li><li>Камано попал в стартовый состав «Локомотива» на матч с «Ахматом»  news.Sportbox…',
    url: 'https://www.championat.com/football/news-4117329-kamano---v-startovom-sostave-lokomotiva-na-match-s-ahmatom.html',
    urlToImage: 'https://img.championat.com/news2/social/0/96/4117329.jpg',
    publishedAt: '2020-08-26T14:10:02Z',
    content: '«» «» 5- .\r\n«»: , , , , , . , , , , , .\r\n: , , , , , , , , , , , .\r\n«»: , , , , , , , , , , .\r\n: , , , , , , , , , , , .\r\n 5- - « » , 18:30 . «» - .\r\n«», 7 4 , 4- , «» (7) 6- . «» (12), «» (11) «» (8… [+1 chars]',
  },
  {
    source: {
      id: null,
      name: 'Championat.com',
    },
    author: 'Чемпионат',
    title: 'Бруно Фукс попрощался с «Интернасьоналом». Бразилец сообщил о переезде в Россию - Чемпионат',
    description: '<ol><li>Бруно Фукс попрощался с «Интернасьоналом». Бразилец сообщил о переезде в Россию  Чемпионат\r\n</li><li>Футбол. Вице-президент "Интернасионала" рассказал о переговорах с ЦСКА по трансферу Фукса  SPORT.RU\r\n</li><li>Вице-президент «Интернасьонала» рассказа…',
    url: 'https://www.championat.com/football/news-4112291-bruno-fuks-poproschalsja-s-internasonalom-brazilec-soobschil-o-pereezde-v-rossiju.html',
    urlToImage: 'https://img.championat.com/news2/social/f/3b/4112291.jpg',
    publishedAt: '2020-08-20T23:50:45Z',
    content: '«» , «».\r\n« . , , , . .\r\n, 8 . «» 20% . «» 2019 . , U23. «» «».',
  },
  {
    source: {
      id: null,
      name: 'Championat.com',
    },
    author: 'Чемпионат',
    title: 'Гол Роналду в ворота «Лиона» признан лучшим в сезоне Лиги чемпионов - Чемпионат',
    description: '<ol><li>Гол Роналду в ворота «Лиона» признан лучшим в сезоне Лиги чемпионов  Чемпионат\r\n</li><li>Футбол. Определён лучший гол сезона в Лиге чемпионов. Видео  SPORT.RU\r\n</li><li>Роскошный выстрел: Роналду забил лучший гол Лиги чемпионов (ВИДЕО)  Телеканал Футб…',
    url: 'https://www.championat.com/football/news-4118207-gol-ronaldu-v-vorota-liona-priznan-luchshim-v-sezone-ligi-chempionov.html',
    urlToImage: 'https://img.championat.com/news2/social/f/08/4118207.jpg',
    publishedAt: '2020-08-27T14:28:30Z',
    content: '-2019/2020. \r\n«» «» (2:1) 1/8 . « » «» (2:1) . \r\n«» «» (2:2), «» «» (2:1) «» «» (3:0).\r\n«» . .\r\n, «» , .',
  },
  {
    source: {
      id: null,
      name: 'Kulichki.net',
    },
    author: null,
    title: 'Экс-президент Ротора Владимир Горюнов: Да кто такой Веретенников?! Я никак не могу понять. - Футбол на Куличках',
    description: '<ol><li>Экс-президент Ротора Владимир Горюнов: Да кто такой Веретенников?! Я никак не могу понять.  Футбол на Куличках\r\n</li><li>«Ротор» — «Спартак»: прогноз Алексея Андронова на матч РПЛ в Волгограде  Чемпионат.com\r\n</li><li>Газизов ответил, попадёт ли Кокор…',
    url: 'https://football.kulichki.net/rusnews/news.htm?616245',
    urlToImage: null,
    publishedAt: '2020-08-26T08:46:13Z',
    content: 'Copyright (c) , 1997-2020.',
  },
  {
    source: {
      id: null,
      name: 'Championat.com',
    },
    author: 'Чемпионат',
    title: 'Арбитр Федотов: «Спартак» должен был перебить пенальти в ворота «Уфы» - Чемпионат',
    description: '<ol><li>Арбитр Федотов: «Спартак» должен был перебить пенальти в ворота «Уфы»  Чемпионат\r\n</li><li>Футбол. "Спартак" принял окончательное решение по поводу участия Кокорина в матче с "Уфой"  SPORT.RU\r\n</li><li>«Спартак» заявляет об игноре темы судей, но что б…',
    url: 'https://www.championat.com/football/news-4111121-arbitr-fedotov-spartak-dolzhen-byl-perebit-penalti-v-vorota-ufy.html',
    urlToImage: 'https://img.championat.com/news2/social/a/26/4111121.jpg',
    publishedAt: '2020-08-19T13:49:49Z',
    content: '«» «».\r\n« , , . VAR, , . . «», , . \r\n. . - . , . . 7,3 », «» .',
  },
  {
    source: {
      id: null,
      name: 'Sports.ru',
    },
    author: null,
    title: 'Фукс попрощался с «Интернасьоналом». Бразилец перейдет в ЦСКА - Sports.ru',
    description: '<ol><li>Фукс попрощался с «Интернасьоналом». Бразилец перейдет в ЦСКА  Sports.ru\r\n</li><li>Бруно Фукс попрощался с «Интернасьоналом». Бразилец сообщил о переезде в Россию  Чемпионат\r\n</li><li>Футбол. Вице-президент "Интернасионала" рассказал о переговорах с Ц…',
    url: 'https://www.sports.ru/football/1088196082.html',
    urlToImage: 'https://www.sports.ru/dynamic_images/news/108/819/608/2/share/c1cf87.jpg',
    publishedAt: '2020-08-21T03:55:00Z',
    content: null,
  },
  {
    source: {
      id: null,
      name: 'Sports.ru',
    },
    author: null,
    title: 'Приоритет «Барсы» – продажа Суареса и Ракитича (Marca) - Sports.ru',
    description: '<ol><li>Приоритет «Барсы» – продажа Суареса и Ракитича (Marca)  Sports.ru\r\n</li><li>Луис Суарес прокомментировал информацию, что «Барселона» на него не рассчитывает  Eurosport.ru\r\n</li><li>Продажа Суареса и Ракитича – приоритет «Барселоны»  Евро-Футбол.Ру\r\n</…',
    url: 'https://www.sports.ru/football/1088260532.html',
    urlToImage: 'https://www.sports.ru/dynamic_images/news/108/826/053/2/share/875710.jpg',
    publishedAt: '2020-08-23T06:10:00Z',
    content: '«» , Marca. \r\n «» (2:8) 1/4 .\r\n, 32- «», «» 2014 .\r\n , , . \r\n , «», 15 .\r\n , «». \r\n« ?» \r\n/MMA/UFC\r\n/\r\n//\r\n/-\r\n-',
  },
  {
    source: {
      id: null,
      name: 'Sports.ru',
    },
    author: null,
    title: 'Варди продлит контракт с «Лестером» до 2023 года. Ему будет 36 лет к концу срока соглашения - Sports.ru',
    description: '<ol><li>Варди продлит контракт с «Лестером» до 2023 года. Ему будет 36 лет к концу срока соглашения  Sports.ru\r\n</li><li>Джейми Варди продлит контракт с «Лестером»  Чемпионат\r\n</li><li>Варди продлил контракт с «Лестером» до 2023 года  news.Sportbox.ru\r\n</li><…',
    url: 'https://www.sports.ru/football/1088366955.html',
    urlToImage: 'https://www.sports.ru/dynamic_images/news/108/836/695/5/share/863f68.jpg',
    publishedAt: '2020-08-26T07:57:00Z',
    content: '«» .\r\n  Sky Sports, «» . 2022 . , «» 2023 .   36 .\r\n, .\r\n 23 «» .',
  },
  {
    source: {
      id: null,
      name: 'Kulichki.net',
    },
    author: null,
    title: 'Андрей Червиченко: Если бы такой пенальти поставили в ворота Спартака, то визг мы бы слышали даже в Хабаровске. - Футбол на Куличках',
    description: '<ol><li>Андрей Червиченко: Если бы такой пенальти поставили в ворота Спартака, то визг мы бы слышали даже в Хабаровске.  Футбол на Куличках\r\n</li><li>«Спартак» вырвал три очка в Волгограде. Спасибо Максименко и перекладине  Чемпионат\r\n</li><li>«Ротор» — «Спар…',
    url: 'https://football.kulichki.net/rusnews/news.htm?616346',
    urlToImage: null,
    publishedAt: '2020-08-26T19:24:34Z',
    content: '«» 5- «» «» (0:1).« ? ? - , . , .\r\n«», . «» , , .\r\n10, . 18- 19- , , , , . », - sport24.ru.',
  },
  {
    source: {
      id: null,
      name: 'Sport.ru',
    },
    author: null,
    title: 'Футбол. "Спартак" согласовал трансфер защитника "Лиона" - SPORT.RU',
    description: '<ol><li>Футбол. "Спартак" согласовал трансфер защитника "Лиона"  SPORT.RU\r\n</li><li>Источник: «Спартак» согласовал трансфер защитника сборной Нидерландов  Чемпионат\r\n</li><li>«Спартак» подпишет правого защитника «Лиона» Тете за 5 млн евро (Telefoot)  Sports.r…',
    url: 'https://www.sport.ru/football/spartak-soglasoval-transfer-zaschitnika-liona/article456266/',
    urlToImage: 'https://www.sport.ru/ai/29x16000/456266/head_0.jpg',
    publishedAt: '2020-08-24T19:45:56Z',
    content: 'Sport.ru/. , "" "" . , "" 5 . . \r\n"" . "" 2017 . € 4 . 24- 18 (9 — ) . , (1 — ). 2015 , 13 .\r\n , ""',
  },
  {
    source: {
      id: null,
      name: 'Championat.com',
    },
    author: 'Чемпионат',
    title: '«Зенит» в «Твиттере» — о «Динамо»: сборная России по регби взяла три очка на «ВТБ Арене» - Чемпионат',
    description: '<ol><li>«Зенит» в «Твиттере» — о «Динамо»: сборная России по регби взяла три очка на «ВТБ Арене»  Чемпионат\r\n</li><li>Итоги 5-го тура РПЛ, Спартак почти догнал Зенит, комментарий  Спорт-Экспресс\r\n</li><li>Меркель запретила болельщикам ходить на футбол в Герма…',
    url: 'https://www.championat.com/football/news-4117849-zenit-sbornaja-rossii-po-regbi-vzjala-tri-ochka-na-vtb-arene.html',
    urlToImage: 'https://img.championat.com/news2/social/2/5b/4117849.jpg',
    publishedAt: '2020-08-27T07:16:48Z',
    content: '- «» «» «» 5- - (0:1).\r\n« , .\r\n : «» . 83- «» .\r\n «» 40- . «» 15- .\r\n«», 5 10 , 4- . «» (12), «» (11) «» (11).',
  },
  {
    source: {
      id: null,
      name: 'Championat.com',
    },
    author: 'Чемпионат',
    title: 'Аллегри может сменить Конте в «Интере» уже на следующей неделе - Чемпионат',
    description: '<ol><li>Аллегри может сменить Конте в «Интере» уже на следующей неделе  Чемпионат\r\n</li><li>Банега сцепился с Конте и поиздевался над его волосами. Тренер воинственно ответил: «Буду ждать тебя после матча»  Sports.ru\r\n</li><li>Аллегри может стать новым главны…',
    url: 'https://www.championat.com/football/news-4113217-allegri-mozhet-smenit-konte-v-intere-uzhe-na-sledujuschej-nedele.html',
    urlToImage: 'https://img.championat.com/news2/social/9/b9/4113217.jpg',
    publishedAt: '2020-08-21T23:08:43Z',
    content: 'The Guardian «» «».\r\n «» , . 51- 53- , 2019 . \r\n, 2014 «». \r\n«» 2- , «» . «» 1:2 (0:1, 1:1), , «» (2:3).',
  },
  {
    source: {
      id: null,
      name: 'Animals.d3.ru',
    },
    author: 'https://animals.d3.ru',
    title: 'Рыбкам не чужда игра в футбол',
    description: 'https://hugelolcdn.com/hugegifs.com/i/13710.gif\n \n \n \n \r\n\n \r\n\n \n\n По нашей дворовой версии "американка".\n\n\n \nНаписал Dr.  YNK\n на animals.d3.ru\n /\n комментировать',
    url: 'https://animals.d3.ru/rybkam-ne-chuzhda-igra-v-futbol-2027141/',
    urlToImage: 'https://cdn.jpg.wtf/futurico/ef/ad/1486584932-efad3e21edd9a2f7259b5aa54e6fbe0a.jpeg',
    publishedAt: '2020-08-20T18:54:48Z',
    content: null,
  },
  {
    source: {
      id: null,
      name: 'Sportbox.ru',
    },
    author: null,
    title: 'Азмун быстрее всех в «Зените» набрал 50 очков по системе «гол+пас». Он побил рекорд Халка - news.Sportbox.ru',
    description: '<ol><li>Азмун быстрее всех в «Зените» набрал 50 очков по системе «гол+пас». Он побил рекорд Халка  news.Sportbox.ru\r\n</li><li>«Зенит» в России играет в режиме «вкл-выкл». Но гол Влашича – лигочемпионский звоночек  Чемпионат\r\n</li><li>Семак: Лимит — зло. Если …',
    url: 'https://news.sportbox.ru/Vidy_sporta/Futbol/Russia/premier_league/spbnews_NI1228672_Azmun_bystreje_vseh_v_Zenite_nabral_50_ochkov_po_sisteme_golpas_On_pobil_rekord_Khalka',
    urlToImage: 'https://s-cdn.sportbox.ru/images/shares/1200x600/node/df/1228672.jpg',
    publishedAt: '2020-08-20T12:51:32Z',
    content: '© « » 2007 2020.16 \r\n «www.sportbox.ru»     ,   ().\r\n № 77-72613  04.04.2018\r\n — www.sportbox.ru\r\n () «www.sportbox.ru»: « »\r\n «www.sportbox.ru»: ..\r\n «www.sportbox.ru»: +7 (495) 653 8419\r\n «www.spor… [+27 chars]',
  },
  {
    source: {
      id: null,
      name: 'Fishki.net',
    },
    author: null,
    title: 'Глоток пенного от болельщика',
    description: 'Глоток пенного от болельщика – Самые лучшие и интересные гифки по теме: Гифки, футбол на развлекательном портале Fishki.net',
    url: 'https://fishki.net/gif/3402558-glotok-pennogo-ot-bolelywika.html',
    urlToImage: 'https://cdn-tn.fishki.net/20/preview/3402558.jpg',
    publishedAt: '2020-08-24T08:20:02Z',
    content: 'kitoff',
  },
  {
    source: {
      id: null,
      name: 'Censor.net.ua',
    },
    author: null,
    title: 'Мы понимаем, насколько важно "сшивать" Украину, и спорт, в частности футбол, решает эту задачу, - Зеленский',
    description: 'Президент Украины Владимир Зеленский считает, что спорт, в частности футбол, помогут "сшить" страну.',
    url: 'https://censor.net.ua/news/3215176/my_ponimaem_naskolko_vajno_sshivat_ukrainu_i_sport_v_chastnosti_futbol_reshaet_etu_zadachu_zelenskiyi',
    urlToImage: null,
    publishedAt: '2020-08-21T11:58:00Z',
    content: null,
  },
  {
    source: {
      id: null,
      name: 'Sports.ru',
    },
    author: null,
    title: '«Ахмат» обыграл «Локомотив» в гостях (3:2), несмотря на два удаления - Sports.ru',
    description: '<ol><li>«Ахмат» обыграл «Локомотив» в гостях (3:2), несмотря на два удаления  Sports.ru\r\n</li><li>«Зенит» не может сломить «Динамо», ЦСКА забил в Краснодаре. 5-й тур РПЛ. LIVE!  Чемпионат\r\n</li><li>«Ахмат» с двумя удалениями одержал победу над «Локомотивом»  …',
    url: 'https://www.sports.ru/football/1088378001.html',
    urlToImage: 'https://www.sports.ru/dynamic_images/news/108/837/800/1/share/98b9a2.jpg',
    publishedAt: '2020-08-26T17:29:00Z',
    content: '5-  «»  «» (2:3).\r\nSports.ru   - .\r\n :   ,   .\r\n«» 5 7 , «» 10 .\r\n26 , 18.30, « »\r\n: \r\n0:1 –\r\n3 , \r\n0:2 –\r\n45 , \r\n1:2 –\r\n48,  , \r\n1:3 –\r\n58 , \r\n2:3 –\r\n77 .\r\n–\r\n, (, 75), , , , , , (, 46), , (, 46), .… [+189 chars]',
  },
  {
    source: {
      id: null,
      name: 'Sport.ru',
    },
    author: null,
    title: 'Футбол. Зайнутдинов покинул "Ростов" и перейдёт в ЦСКА - SPORT.RU',
    description: '<ol><li>Футбол. Зайнутдинов покинул "Ростов" и перейдёт в ЦСКА  SPORT.RU\r\n</li><li>ЦСКА объявил о трансфере хавбека Зайнутдинова. Контракт – на 5 лет  Sports.ru\r\n</li><li>ЦСКА объявил о переходе Бактиёра Зайнутдинова  Чемпионат\r\n</li><li>Зайнутдинов покинул «…',
    url: 'https://www.sport.ru/football/zaynutdinov-pokinul-rostov-i-pereydet-v-tsska/article456239/',
    urlToImage: 'https://www.sport.ru/ai/29x16000/456239/head_0.png',
    publishedAt: '2020-08-24T15:37:25Z',
    content: null,
  },
];

export default articles;
